### PR TITLE
Versioned stubs workflow

### PR DESCRIPTION
**Pull request by tillkruss**
Automate stubs for https://github.com/JetBrains/phpstorm-stubs/pull/1514

### CODE REVIEW

**Comment by szepeviktor** [comment]
docs: https://github.com/JetBrains/phpstorm-stubs/blob/master/CONTRIBUTING.md#typehints-in-signature

**Comment by szepeviktor** [comment]
Rector downgrades it to lower PHP versions. (does 99% of the downgrade)
```php
<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\DowngradeLevelSetList;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->paths([
        __DIR__ . '/src',
    ]);

    $rectorConfig->sets([
        DowngradeLevelSetList::DOWN_TO_PHP_74
    ]);
};
```

```diff
@@ @@
      * @return array|false
      */
     #[\Relay\Attributes\RedisCommand]
-    public function getMasterAddrByName(string $master): array|false;
+    public function getMasterAddrByName(string $master);

     /**
      * Returns the state and info of the specified master.
```

**Comment by szepeviktor** [comment]
@tillkruss What is up here?
What is your plan?

**Comment by tillkruss** [comment]
Not sure, waiting for the merge upstream.

**Pull request closed without merging**
